project:
  type: book

book:
  title: "GCP Shiny Booklet"
  author: "Eric Ekholm"
  date: "4/22/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: background.qmd
      chapters:
        - shiny_background.qmd
        - gcp_background.qmd
        - why_gcp.qmd
        - hello_world.qmd
    - part: shiny.qmd
      chapters:
        - create_proj.qmd
        - basic_app.qmd
    - part: containers.qmd
      chapters:
        - docker.qmd
        - cloudbuild.qmd
    - part: cloud_sql.qmd
      chapters:
        - sql_setup.qmd
        - sql_create.qmd
    - part: cloud_run.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
  pdf:
    documentclass: scrreprt



