project:
  type: book

book:
  title: "GCP Shiny Booklet"
  author: "Eric Ekholm"
  date: "4/22/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - part: background.qmd
      chapters:
        - shiny_background.qmd
        - gcp_background.qmd
        - why_gcp.qmd
    - part: hello_world.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
  pdf:
    documentclass: scrreprt



